export const HOST = "localhost";
export const USER = "";
export const PASSWORD = "";
export const DATABASE = "noveve";
export const SECRET = "0c7Op12o2L$n0v3vE"
export const METHOD = "http";
export const DOMAIN = "localhost:4057/noveve-api";
export const PORT = 4057;
export const  USER_EMAIL = "";
export const PASSWORD_EMAIL = "";
export const IS_DEVELOPMENT = true;
export const KEY_FILE = "/home/springlabs/certificados/springlabsdevs.net.key";
export const CERT_FILE = "/home/springlabs/certificados/springlabsdevs.net.trust.cer";
export const API_PREFIX = "noveve-api"
export const STATICS_URL = "../../statics/images" //RUTA PARA GUARDAR LAS IMÁGENES DE USUARIOS
export const STATICS_EVENTS = "../../statics/images" // RUTA PARA GUARDAR LOAS IMÁGENES DE LOS EVENTOS
export const STATICS_SIGNATURES = "../../statics/signatures"
export const STATICS_EXCEL = "../../statics/excel"